// This file is generated by icon spritesheet generator

export const iconNames = [
  "Twitter",
  "Twitch",
  "Linkedin",
  "Instagram",
  "Home",
  "Github",
] as const

export type IconName = typeof iconNames[number]
